2Fake/devolo_home_control_api

devolo_home_control_api/homecontrol.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/publisher/updater.py, docs/CHANGELOG.md, tests/mocks/mock_homecontrol.py, tests/mocks/mock_remote_control.py, tests/test_data.json, tests/test_homecontrol.py, tests/test_remote_control_property.py, tests/test_updater.py
=> Remote control

devolo_home_control_api/backend/__init__.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/publisher/updater.py, tests/mocks/mock_mprm.py, tests/test_homecontrol.py, tests/test_updater.py
=> Test hasattr

.devcontainer/devcontainer.json, .github/workflows/pythonpackage.yml, devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/helper/uid.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/properties/binary_sensor_property.py, devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/humidity_bar_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/sensor_property.py, devolo_home_control_api/properties/settings_property.py, devolo_home_control_api/publisher/publisher.py, devolo_home_control_api/publisher/updater.py, tests/fixtures/mprm.py, tests/fixtures/publisher.py, tests/mocks/mock_mprm.py, tests/mocks/mock_websocket.py, tests/mocks/mock_websocketapp.py, tests/stubs/mprm.py, tests/stubs/mprm_websocket.py, tests/test_mprm_websocket.py, tests/test_updater.py
=> Add pylint and mypy to the CI

.github/workflows/pythonpackage.yml
=> Fix formatting

devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/mydevolo.py, tests/fixtures/mprm.py, tests/stubs/mprm.py, tests/stubs/mprm_websocket.py, tests/test_mprm.py, tests/test_mprm_websocket.py
Rebrowse the network via mDNS if there are connection exceptions.
=> Handle IP address change

.pre-commit-config.yaml, README.md, devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/homecontrol.py, setup.py, tests/test_mprm_websocket.py
Bump websocket version to 0.58.0
=> Bump websocket version

docs/CHANGELOG.md
=> Prepare Release

devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/publisher/updater.py, docs/CHANGELOG.md, tests/fixtures/mprm.py, tests/fixtures/requests.py, tests/mocks/mock_response.py, tests/test_mprm.py
Handle more timeouts, if a gateway is inaccessible.
=> Handle more timeouts, if a gateway is inaccessible

devolo_home_control_api/backend/mprm_websocket.py, docs/CHANGELOG.md
Fix on_pong in case an old version of websocket_client is used.
=> Fix on_pong

devolo_home_control_api/__init__.py, docs/CHANGELOG.md
=> Fix version

.github/workflows/pythonpackage.yml, devolo_home_control_api/__init__.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/properties/binary_sensor_property.py, devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/humidity_bar_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/sensor_property.py, devolo_home_control_api/properties/settings_property.py, docs/CHANGELOG.md, tests/test_mprm.py
websocket-client 1.1.0 changes signatures again.
=> Support new websocket-client version

.github/workflows/pythonpackage.yml
This MR bumps the pre-commit workflow to version 2.0.3. Fixes #98
=> bump pre-commit workflow

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml
=> Fix build with pyproject.toml

devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/devices/gateway.py, devolo_home_control_api/devices/zwave.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/mydevolo.py, devolo_home_control_api/properties/binary_sensor_property.py, devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/humidity_bar_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/sensor_property.py, devolo_home_control_api/properties/settings_property.py, devolo_home_control_api/publisher/publisher.py, devolo_home_control_api/publisher/updater.py, docs/CHANGELOG.md, tests/test_mydevolo.py
Home Assistant needs stricter typing.
=> Stricter typing

.github/workflows/pythonpackage.yml
=> Add Python 3.11 to CI

devolo_home_control_api/backend/mprm.py
Change zeroconf type that is searched for to detect the gateway locally. If there are a lot devices offering http but only few devolo devices, this should be faster. Downside is, that gateways running firmware versions older than 2 years will not be discovered. However, I assume those firmware version are not in use any longer.
=> Change zeroconf type

devolo_home_control_api/mydevolo.py, tests/test_mydevolo.py
=> Use cache for gateways

devolo_home_control_api/backend/mprm_rest.py
=> Fix boolean traps in function calls

devolo_home_control_api/__init__.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/properties/binary_sensor_property.py, devolo_home_control_api/properties/humidity_bar_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/settings_property.py, pyproject.toml
=> Improve Typing

devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/devices/gateway.py, devolo_home_control_api/exceptions/__init__.py, devolo_home_control_api/exceptions/device.py, devolo_home_control_api/exceptions/general.py, devolo_home_control_api/mydevolo.py, devolo_home_control_api/properties/binary_sensor_property.py, devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/humidity_bar_property.py, devolo_home_control_api/properties/multi_level_sensor_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/settings_property.py, tests/test_homecontrol.py, tests/test_metering_plug.py, tests/test_mydevolo.py, tests/test_websocket.py
=> Improve exceptions

devolo_home_control_api/devices/zwave.py, devolo_home_control_api/helper/__init__.py, devolo_home_control_api/helper/string.py, devolo_home_control_api/helper/uid.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/publisher/updater.py
=> Improve helper

devolo_home_control_api/backend/mprm_rest.py
=> Use enum for mPRM response status

devolo_home_control_api/devices/zwave.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/properties/__init__.py, devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/sensor_property.py
=> Improve imports of properties

devolo_home_control_api/backend/__init__.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/devices/__init__.py, devolo_home_control_api/devices/gateway.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/properties/property.py, devolo_home_control_api/publisher/updater.py
=> Improve imports

devolo_home_control_api/backend/mprm_websocket.py, pyproject.toml
=> Use typing-extensions for Python < 3.11 only

devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, devolo_home_control_api/properties/settings_property.py, docs/CHANGELOG.md, tests/fixtures/homecontrol_motion_sensor.json, tests/fixtures/homecontrol_remote_control.json, tests/fixtures/homecontrol_siren.json, tests/fixtures/homecontrol_thermostat.json, tests/test_metering_plug.py, tests/test_motion_sensor.py, tests/test_siren.py, tests/test_thermostat.py, tests/test_wall_switch.py
Set methods of properties returned None. However, the can return a boolean to indicate, if setting was successful or not.
=> Improve set methods of properties

.github/workflows/pythonpackage.yml
=> Upload coverage only for one Python version

devolo_home_control_api/mydevolo.py, devolo_home_control_api/publisher/__init__.py, devolo_home_control_api/publisher/publisher.py, devolo_home_control_api/publisher/updater.py
=> Improve docstrings

devolo_home_control_api/mydevolo.py, tests/test_mydevolo.py
=> Remove cache from getting gateway id

devolo_home_control_api/homecontrol.py, devolo_home_control_api/publisher/__init__.py, tests/test_homecontrol.py, tests/test_publisher.py
=> Improve publisher import

devolo_home_control_api/backend/mprm.py, devolo_home_control_api/backend/mprm_rest.py, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/devices/gateway.py, devolo_home_control_api/devices/zwave.py, devolo_home_control_api/helper/uid.py, devolo_home_control_api/homecontrol.py, devolo_home_control_api/mydevolo.py, devolo_home_control_api/properties/consumption_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/settings_property.py, devolo_home_control_api/publisher/publisher.py, devolo_home_control_api/publisher/updater.py, tests/__init__.py, tests/mocks/mock_websocket.py, tests/mocks/mock_zeroconf.py
Use future annotations. Fixes ruff rule FA100.
=> Use future annotations

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, devolo_home_control_api/backend/mprm_websocket.py, devolo_home_control_api/properties/consumption_property.py
=> Add Python 3.12 to CI

devolo_home_control_api/properties/binary_switch_property.py, devolo_home_control_api/properties/multi_level_switch_property.py, devolo_home_control_api/properties/remote_control_property.py, pyproject.toml
=> Fix ruff findings

.github/workflows/pythonpackage.yml, tests/snapshots/test_mydevolo.ambr
=> Remove unused snapshot

.github/workflows/pythonpackage.yml
=> Fix coverage reporting

.github/workflows/pythonpackage.yml
=> Cover Ubuntu update in CI

.github/workflows/pythonpackage.yml
=> Run tests on Python 3.14
